name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Fixed typo here

      - name: Run tests
        run: |
          # Add commands to run your tests here, e.g. pytest
          echo "Add your test commands here"

      - name: Build Docker image
        run: |
          docker build -t iris_model_app .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag iris_model_app vikaskarbail/iris_model_app:latest  # Replace with your Docker Hub username
          docker push vikaskarbail/iris_model_app:latest  # Same here
